MKN BNK PBU LTI PKJ XEM CK
*MK NBN KPB ULT IPK JXE MCK
**M KNB NKP BUL TIP KJX EMC K

FEO UHL IVV ENJ IEK QYN VE
*FE OUH LIV VEN JIE KQY NVE
**F EOU HLI VVE NJI EKQ YNV E

MKR BNO PBY LTM PKN XEQ CK
*MK RBN OPB YLT MPK NXE QCK
**M KRB NOP BYL TMP KNX EQC K


