YYV NBS BPC XHQ BYR JSU OY
*KY YNV MBF ITT MKU UEX ZKI
**K BYH PMR LEF PVG XPJ CVU V

FEU UHR IVB ENP IEQ QYT VE
*RE XUB LIL HAZ LRA TLD YRO
**R HXO VLY RDM VUN DOQ IUB B

YYR NBO BPY XHM BYN JSQ OY
*KY UNV IBF ETT IKU QEX VKI
**K BUH PIR LAF PRG XLJ CRU V


